### ISSUE TITLE
Asking for feedback & feature requests in youtube-search-python

### ISSUE THREAD

**Issue by alexmercerind** [tobip/mini-youtube-player#1]
Hi there @tobip!
First of all, really nice command-line music player.

What I wanna share with you is that, I have spent time rewriting & making youtube-search-python more informational (giving more informational search results), maintainable (making bug fixes easier) & understandable (making users to understand & contribute to the code easily). 
After bunch of rewrite, I pushed my code to main branch of my repo. 

I'm here to ask for your feedback to the new additions & changes. 
Please let me know, if there is something that you wanna see coming. As I'm rewriting a lot of things, so it will be easier to add things.

Checkout new example [here](https://github.com/alexmercerind/youtube-search-python/blob/main/example.py).

**Major additions and improvements are**

- Now the search result contains a lot more information than before & in an more aligned manner.
- Now you can search for channels.
- Now you can now perform a "general search" on YouTube i.e. to get all types of results like videos, playlists & channels at once (like a generic result from YouTube is). Earlier you could just search for playlist or videos at a time. Now you can search for all the things, at the same time.
- Now you can perform custom searches using ```CustomSearch``` class i.e apply search filters etc. See example for more info .
- I have made the code a lot more maintainable & easier for users to understand.
- And, as always youtube-search-python is dependencies free. 🎉️

As you might be thinking, "I have to rewrite a lot of things now", but no old methods & classes i.e. ```SearchVideos``` & ```SearchPlaylists``` are still present for you to use. But, I'll recommend to use new classes as it will make your work easier as well in way (like giving two types of view counts etc.)

Thankyou. Please let me know.

**Comment by tobip** [comment]
Awesome, yes I saw your updates and i will definitely will look into them next week.  
Right now I am working on a different project.  
I will keep you updated.
